source :rubygems
gem 'kramdown',   '~>0.13'
gem 'nanoc',      '~>3.1'
gem 'deadweight', '~>0.2'
gem 'rainpress',  '~>1.0'
gem 'typogruby',  '~>1.0'
gem 'jsmin',      '~>1.0'
gem 'builder',    '~>2.1'
gem 'rack',       '~>1.2'
gem 'adsf',       '~>1.0'
gem 'nanoc-cachebuster'
gem 'coffee-script'
gem 'sass',       '~>3.1'
