source :rubygems
gem 'kramdown',   '~>0.10'
gem 'nanoc',      '~>3.1'
gem 'deadweight', '~>0.1'
gem 'rainpress',  '~>1.0'
gem 'typogruby',  '~>1.0'
gem 'jsmin',      '~>1.0'
gem 'builder',    '~>2.1'
gem 'rack',       '~>1.2'
gem 'adsf',       '~>1.0'
gem 'nanoc-cachebuster'
gem 'coffee-script'
