source 'https://rubygems.org'

gem 'nanoc',                '~>3.4'
gem 'kramdown',             '~>0.14'
gem 'deadweight',           '~>0.2'
gem 'rainpress',            '~>1.0'
gem 'typogruby',            '~>1.0'
gem 'jsmin',                '~>1.0'
gem 'builder',              '~>3.1'
gem 'rack',                 '~>1.4'
gem 'adsf',                 '~>1.1'
gem 'nanoc-cachebuster',    '~>0.3'
gem 'coffee-script',        '~>2.2'
gem 'sass',                 '~>3.1'